### ISSUE TITLE
Jnaerator fail to handle python include (Py_ssize_t)

### ISSUE THREAD

**Issue by twitwi** [nativelibs4java/nativelibs4java#383]
I have a python wrapper that I used to build with jnaerator 0.9.9 and bridj 0.6.1.

I tried switching to 0.11 and I had to add the -parseChunks option to get proper generation.
(same with 0.12-SNAPSHOT)

Then when I compile the files I get some errors of this kind:

```
 com/heeere/python27/Python27Library.java:1811: error: incompatible types
     return Pointer.pointerToAddress(PyGC_Collect$2());
                                    ^
required: Pointer<Py_ssize_t>
found:    Pointer<CAP#1>
where CAP#1 is a fresh type-variable:
  CAP#1 extends Object from capture of ?
```

What I know is that in previous versions, it was compiling fine BUT the Py_ssize_t was wrongly handled (it was considered as a pointer instead of a "long" if I remember correctly). Here is the c definition :

```
 /* Py_ssize_t is a signed integral type such that sizeof(Py_ssize_t) ==
  * sizeof(size_t).  C99 doesn't define such a thing directly (size_t is an
  * unsigned integral type).  See PEP 353 for details.
  */
 #ifdef HAVE_SSIZE_T
 typedef ssize_t         Py_ssize_t;
 #elif SIZEOF_VOID_P == SIZEOF_SIZE_T
 typedef Py_intptr_t     Py_ssize_t;
 #else
 #   error "Python needs a typedef for Py_ssize_t in pyport.h."
 #endif
```

Any idea on how to solve or track the problem?
